// internal/scaffold/readme.go
package scaffold

import (
	"bytes"
	"os"
	"path/filepath"
	"text/template"

	"devinit/internal/config"
)

type ReadmeStep struct{}

func (r *ReadmeStep) Name() string { return "README.md" }

func (r *ReadmeStep) Run(cfg *config.ProjectConfig) error {
	const tmplStr = `# {{.ProjectName}}

> Generated by [devinit](https://github.com/yourusername/devinit)

## Getting started

` + "```" + `bash
# Clone the repo
git clone [https://github.com/](https://github.com/){{.GitHubUser}}/{{.ProjectName}}
cd {{.ProjectName}}
` + "```" + `

## Tech stack

- Language: **{{.Language}}**
{{- if .CreateDocker}}
- Docker: Dockerfile included
{{- end}}
{{- if .CreateCI}}
- CI/CD: GitHub Actions workflow included
{{- end}}
`

	tmpl := template.Must(template.New("readme").Parse(tmplStr))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return err
	}

	path := filepath.Join(cfg.ProjectName, "README.md")
	return os.WriteFile(path, buf.Bytes(), 0644)
}