// internal/scaffold/readme.go
package scaffold

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"devinit/internal/config"
)

type ReadmeStep struct{}

func (r *ReadmeStep) Name() string { return "README.md" }

func (r *ReadmeStep) Run(cfg *config.ProjectConfig) error {
	path := filepath.Join(cfg.ProjectName, "README.md")

	// 1. Attempt AI Generation First (if requested)
	if cfg.GenerateAIReadme {
		fmt.Println("  🤖 Generating intelligent README via Gemini...")
		aiContent, err := GenerateAIReadme(cfg) // Calls the function from ai.go
		
		if err == nil {
			// Success! Write the AI content and exit the step
			return os.WriteFile(path, []byte(aiContent), 0644)
		}
		
		// If AI fails (e.g., missing API key, network error), don't crash.
		// Print a warning and fall through to the standard template.
		fmt.Printf("  ⚠️ AI generation failed: %v\n  Falling back to standard template...\n", err)
	}

	// 2. Standard Template Fallback
	const tmplStr = `# {{.ProjectName}}

> Generated by [devinit](https://github.com/yourusername/devinit)

## Getting started

` + "```" + `bash
# Clone the repo
git clone [https://github.com/](https://github.com/){{.GitHubUser}}/{{.ProjectName}}
cd {{.ProjectName}}
` + "```" + `

## Tech stack

- Language: **{{.Language}}**
{{- if .CreateDocker}}
- Docker: Dockerfile included
{{- end}}
{{- if .CreateCI}}
- CI/CD: GitHub Actions workflow included
{{- end}}
`

	tmpl := template.Must(template.New("readme").Parse(tmplStr))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return err
	}

	return os.WriteFile(path, buf.Bytes(), 0644)
}